### PR TITLE
Fix gdal-warp -ovr ports

### LINKED ISSUE #3196: Conform to GDAL Warp -ovr Overview Selection Options
The `OverviewStrategy` trait and subclasses (https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala) exist to capture the gdal warp command line `-ovr` options (https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-ovr)

We currently represent `Auto-N` and `None` (`Base` as we've named things) but do not represent explicit overview level selection *or* for that matter, the default GDAL behavior of `Auto` (`AutoHigher` behaves slightly differently). The `OverviewStrategy` types should work as they are described in GDAL docs

### PR DESCRIPTION
**Pull request by moradology**
# Overview

This PR exposes the overview selection logic implicit in each of the `OverviewStrategy` instances by way of a `selectOverview` method. Now, instead of matching and requiring users of the sum type to implement logic themselves, a call to `selectOverview` with the available `CellSizes` and the desired `CellSize` will yield a selection of the `CellSize` corresponding to the selected `Overview`

## Checklist

- [x] [docs/CHANGELOG.rst](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary
- [x] `docs` guides update, if necessary
- [x] New user API has useful Scaladoc strings
- [x] Unit tests added for bug-fix or new feature

## Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

Closes #3196

### CODE REVIEW

File: gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala [hunk 1]
```diff
@@ -100,8 +100,11 @@ object GDALUtils {
     }
 
   def deriveOverviewStrategyString(strategy: OverviewStrategy): String = strategy match {
+    case Auto(n) if (n == 0) => "AUTO"
     case Auto(n) => s"AUTO-$n"
-    case AutoHigherResolution => "AUTO"
+    case Level(level) => s"$level"
     case Base => "NONE"
+    case other =>
```
Comment (pomadchin) [inline gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala]: This would never happen, it is an exhaustive match on a sealed trait.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 2]
```diff
@@ -16,21 +16,78 @@
...
+import geotrellis.raster.CellSize
+
+import scala.collection.Searching._
+
+/**
+  * Options ported from GDAL (https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-ovr)
+  *  for automatic selection from among available overviews
+  */
+sealed trait OverviewStrategy {
+  def selectOverview(overviewCS: List[CellSize], desiredCS: CellSize): CellSize
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: Hm, we don't need this function in case of GDAL; do you think this is an appropriate place for selecting overview? 

This function is specific to the interpretation of the `OverviewStrategy` AST, and it is not a member of an AST that will work for all interpreters the same way. 

i.e. `GDALUtils.deriveOverviewStrategyString` lives in its own object, which is an interpreter for this AST.

What do you think about moving it in a separate object since it would be used only with GeoTrellis GeoTiffs?

File: raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala [hunk 3]
```diff
@@ -0,0 +1,59 @@
+package geotrellis.raster.io.geotiff
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala]: could you generate a header for tests? via `test:headerCreate`

File: raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+
+import geotrellis.raster._
+
+import org.scalatest._
+
+class OverviewStrategySpec extends FunSpec with Matchers {
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala]: +1000 for Specs :+1:

File: gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala (hunk 1 above)
Comment (moradology) [reply gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala]: We still have `AutoHigher`, but that has no GDAL string interpretation which makes sense. Is your proposal that it be removed so that this check is once again exhaustive?

Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala]: Ah I forgot about that; :+1: than.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala (hunk 2 above)
Comment (moradology) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: So far, the overview selection I've seen is pretty consistently be expressible in terms of the `selectOverview` method and this way of organizing things keeps the AST and the info necessary to make sense of it together + avoids duplication of some case-handling logic. I'm not opposed to our handling the overview selection case in a more general/appropriate fashion and therefore hiding this away for occasions where GDAL interop are required, but that seems like a different PR with a larger footprint.

File: gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala (hunk 1 above)
Comment (pomadchin) [reply gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala]: Hm, do we need to throw, or warning + a fallback behavior? (default GDALWapr)

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala (hunk 2 above)
Comment (pomadchin) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: Hm, Is it correct to consider GDAL an "interop" thing? It could be an acceptable implementation if we were not using the same AST for GDAL. Moving all the specific to interpreter thing into interpreter looks pretty convenient btw (throwing here the RasterSources Query DSL). 

I'm happy to discuss it though.

File: raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala (hunk 3 above)
Comment (pomadchin) [reply raster/src/test/scala/geotrellis/raster/io/geotiff/OverviewStrategySpec.scala]: It is broken now, created an issue https://github.com/locationtech/geotrellis/issues/3201

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala (hunk 2 above)
Comment (echeipesh) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: I think the point is somewhat academic and I'm not sure I'd have regrets in my life with either choice.

However, if I had to pick one I'd go with moving the `selectOverview` function to be on the companion object of`OverviewStrategy`. I have two soft reasons for feeling that way:

As @pomadchin mentions the purpose of this ADT is to select behavior. At the moment indication this selection to our GDAL bindings is "first class" intention of this ADT. Having a method that appears to do that on the instances of the ADT is slightly misleading because it could never be used by GDAL bindings.

This also reminds me of similar design choice made in [`ResampleTarget`](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/ResampleTarget.scala) where the `apply` function does the job of creating the target `GridExtent`. I had to write some code that interpreted it in terms of old `Reproject.Options` and I found it hard to think through correctness there because trying to fit in the use of `apply` seemed it was a good thing. In the end I had to write interpretations of `ResampleTarget` over `Reproject.Options` that ignored the implementations of the `apply` method:

https://github.com/locationtech/geotrellis/blob/3e59f26807fc9d3a2dbf47fe358a1f1dbd2205ae/raster/src/main/scala/geotrellis/raster/ResampleTarget.scala#L87-L96

So in my mind that's the case where putting methods on ADT made it worse for interpreting the semantics between two similar domains for that ADT.

So perhaps the code reuse could be served by:

```scala
// before
val sourceCS = strategy.selectOverview(overviews.map(_.cellSize), cellSize)

// after
val sourceCS = OverviewStrategy.select(overviews.map(_.cellSize), cellSize, strategy)
```

Or even perhaps:
```scala
object OverviewStrategy {
   def select[A](overviews: A, desiredCS: CellSize, strategy: OverviewStrategy)(implicit ev: A => CellSize): A = {...}
}
```

Comment (echeipesh) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: Reading between the lines I think this is going in the direction where we end up with two ways of selecting overviews: 

1. `GDALOverviewStrategy` which is basically what we have now
2. `OverviewStrategy` is that is JVM first in lines with #3194 (non-sealed with interface)

And there is a partial function `OverviewStrategy => GDALOverviewStrategy` that is used by `GDALRasterSource`.

Comment (moradology) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: "Interop" might not be the right word choice In general, I like the interpreter pattern a lot but I'm not sure I see the appeal of separating out implementation from the 'language' (which in this case is just selection from among a few overview strategies) but here I don't fully see the appeal. I think that the AST's meaning is better documented to the extent that you can track down the code which will be called in case that option is supplied.

I think we might want more opinions to weigh in

Comment (moradology) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: Having discussed this at length with @echeipesh and @pomadchin, I've removed `OverviewStrategy` methods in favor of a function on the companion object.

File: gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala (hunk 1 above)
Comment (moradology) [reply gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala]: I've gone with your suggestion of falling back on a sensible default and warning

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 5]
```diff
@@ -16,20 +16,75 @@
...
+    strategy: OverviewStrategy
+  ): Int = strategy match {
+    case Level(overviewIdx) =>
+      overviewIdx
+    case Auto(n) =>
+      selectIndexByProximity(overviewCS, desiredCS, 0.5) + n
+    case Base =>
+      overviewCS.indexOf(overviewCS.min)
+    case AutoHigherResolution =>
+      selectIndexByProximity(overviewCS, desiredCS, 1.0)
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: Waiting for Travis to be happy with this change. This behavior should match to the tested old behavior (the old one had a long testing path).

File: layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala [hunk 6]
```diff
@@ -59,22 +59,24 @@ class GeoTiffReprojectRasterSourceSpec extends FunSpec with RasterMatchers with
...
 
       val thriceFuzzyLayout = {
         val CellSize(width, height) = baseReproject.cellSize
         LayoutDefinition(RasterExtent(LatLng.worldExtent, CellSize(width*3.5, height*3.5)), tileSize = 256)
       }
 
       val thriceFuzzySource = rasterSource.reprojectToGrid(LatLng, thriceFuzzyLayout).asInstanceOf[GeoTiffReprojectRasterSource]
-      thriceFuzzySource.closestTiffOverview.cellSize shouldBe CellSize(20,20)
+      thriceFuzzySource.closestTiffOverview.cellSize.width shouldBe 40.0 +- 0.1
+      thriceFuzzySource.closestTiffOverview.cellSize.height shouldBe 40.0 +- 0.1
```
Comment (moradology) [inline layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala]: This change is necessary as the former expectation (always round up to higher resolution levels) was baked in and doesn't correctly track GDAL behavior

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala (hunk 5 above)
Comment (moradology) [reply raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala]: The tests turned out to require a bit more attention than I'd anticipated as some of them baked in the `AutoHigher` behavior rather than `Auto`

File: layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala (hunk 6 above)
Comment (pomadchin) [reply layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala]: These are AutoHigher tests, let's keep them working with AutoHigher strategy? And this one cxan be a new test (this is just a sainity check that we could preserve the old behavior), how do you feel about it?

File: layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala [hunk 7]
```diff
@@ -59,22 +59,24 @@ class GeoTiffReprojectRasterSourceSpec extends FunSpec with RasterMatchers with
...
 
       val quatroFuzzyLayout = {
         val CellSize(width, height) = baseReproject.cellSize
         LayoutDefinition(RasterExtent(LatLng.worldExtent, CellSize(width*4.1, height*4.1)), tileSize = 256)
       }
 
       val quatroTimesFuzzySource = rasterSource.reprojectToGrid(LatLng, quatroFuzzyLayout).asInstanceOf[GeoTiffReprojectRasterSource]
+      println("TARGET", quatroFuzzyLayout.cellSize)
```
Comment (pomadchin) [inline layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala]: Probably should not be there

Comment (moradology) [reply layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala]: Well, that's a bit sloppy.

File: store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala [hunk 8]
```diff
@@ -139,25 +139,12 @@ object GeoTrellisRasterSource {
...
-          .headOption
-          .orElse(maxResultion)
-      case Auto(n) =>
-        val sorted = grids.sortBy(v => math.abs(cellSize.resolution - f(v).resolution))
-        sorted.lift(n).orElse(sorted.lastOption) // n can be out of bounds,
-      // makes only overview lookup as overview position is important
-      case Base => maxResultion
-    }
+    strategy: OverviewStrategy = OverviewStrategy.DEFAULT
+  )(implicit f: T => CellSize): T = {
```
[the remark this answers is not in the document]
Comment (CloudNiner) [reply store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala]: Ah, should have mentioned this sooner. 

It was Option[Int] because some operations could return an out of bounds index.  It's not clear how GDAL handles this situation, so we decided that it would be simpler if OverviewStrategy.selectOverview always returned an in bounds index. Which it now does due to additional error handling there. Before this change, we were doing an `option.get` everywhere which just pushes the throw further down. In that case, I wasn't sure how we would even handle getting a bad overview. 

I can add some additional docstrings to note that selectOverview should always return a clamped index, this was apparently the intent of the code based [on a test](https://github.com/locationtech/geotrellis/pull/3200/files#diff-28fce00d2a6d9757847488e95fe46c87R194) that predates me picking this task up.

File: spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala [hunk 9]
```diff
@@ -95,11 +95,14 @@ class GeoTrellisRasterSourceSpec extends FunSpec with RasterMatchers with GivenW
...
-          // resample to 0.9 so RasterSource picks the base layer and not an overview
+          .resample(sourceMultiband.cols.toInt, sourceMultiband.rows.toInt, NearestNeighbor)
 
-      val resampledSource =
-        sourceMultiband.resample(expected.tile.cols, expected.tile.rows, NearestNeighbor)
+      val resampledSource = sourceMultiband.resample(
+        expected.tile.cols,
+        expected.tile.rows,
+        NearestNeighbor,
+        strategy = Base
```
[the remark this answers is not in the document]
Comment (CloudNiner) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: It was. When Nathan and I dug into this, we'd always get a raster at the base cell size. So it seems more correct to remove the fudge factor that attempts to get a non-base resolution and just have the resample operation pick the Base overview explicitly. 

Similar issue for the reproject test. When we load a raster with the GeoTiff method and then use reproject instead of resample method, that doesn't allow us to select an overview strategy since reproject doesn't care about that fundamentally. So again, we just use Base where necessary to preserve the idea that when we load the expected raster we're always dealing with the base resolution.

Hopefully that makes sense, we can discuss offline if more detail is necessary.

[the remark this answers is not in the document]
Comment (CloudNiner) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: I did revert to using AutoHigher in the RasterSourceRDD specs, since in those cases we load both in a way that we're resampling anyways.

File: store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (pomadchin) [reply store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala]: When it can’t fine an overview the idea was to use the Base layer, since it looks like what GDAL does.

File: spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (pomadchin) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: @CloudNiner i would like to revert all the strategies to AutoHigher; to preserve the old tests. This strategy is pretty important for RF and if we need more tests, lest create new tests without killing the old ones; how do you feel about that?

[the remark this answers is not in the document]
Comment (pomadchin) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: I mean just as a check that the behavior of old functions did not change; if we’ll change tests, it is hard to say, was the old behavior preserved or not.

File: spark/src/test/scala/geotrellis/spark/RasterSourceRDDSpec.scala [hunk 10]
```diff
@@ -141,8 +140,9 @@ class RasterSourceRDDSpec extends FunSpec with TestEnvironment with RasterMatche
     }
 
     it("should reproduce tileToLayout followed by reproject") {
+      val reprojectedRasterSource = rasterSource.reprojectToGrid(targetCRS, layout, strategy = Base)
       val reprojectedSourceRDD: MultibandTileLayerRDD[SpatialKey] =
-        RasterSourceRDD.spatial(rasterSource.reprojectToGrid(targetCRS, layout), layout)
+        RasterSourceRDD.spatial(Seq(reprojectedRasterSource), layout, strategy = Base)
```
[the remark this answers is not in the document]
Comment (CloudNiner) [reply spark/src/test/scala/geotrellis/spark/RasterSourceRDDSpec.scala]: Yeah reverted rastersourcerdd to AutoHigher

File: spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (CloudNiner) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: Then theres a chunk of extra work here to get this build green, as I'm not sure how to get GeoTiffReader.readMultiband to be explicit about not choosing the Base cell size for its operations. It might be best if someone else takes that work on at this point.

File: store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (CloudNiner) [reply store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala]: How does that reconcile with the idea that we've decided to include the base layer in the resolutions list in all RasterSource implementations?

[the remark this answers is not in the document]
Comment (CloudNiner) [reply store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala]: Perhaps this discussion should be moved offline as well?

File: spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (pomadchin) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: @CloudNiner how is that possible that old operations can't work as they worked before with AutoHigher? What has changed?

File: store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala (hunk 8 above)
[the remark this answers is not in the document]
Comment (CloudNiner) [reply store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala:143]: After a discussion we decided on the following:
- Revert OverviewStrategy.DEFAULT = AutoHigherResolution to make the default consistent with the old behavior for now. We'll address changing the default at a later date
- Update AutoHigherResolution implementation to match the docstring and old behavior, and verify it with tests
- OverviewStrategy.selectOverview still clamps to available indices. Each overview strategy can perform custom clamping behavior, like AutoHigher above, but in the absence of that, the index will be clamped to the nearest valid value, e.g. -1 -> 0 or list.size + 5 -> list.size - 1
- Revert tests where possible to use the AutoHigher default in order to appropriately test the old behavior.

File: spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala (hunk 9 above)
[the remark this answers is not in the document]
Comment (CloudNiner) [reply spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala]: After a discussion and the adjustments made that were discussed in https://github.com/locationtech/geotrellis/pull/3200#discussion_r401672704, @pomadchin is going to dig deeper as to why a number of tests are still failing.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 11]
```diff
@@ -16,20 +16,95 @@
...
+    }
+    if (maybeIndex < 0) 0
+    else if (maybeIndex >= overviewCS.size) overviewCS.size - 1
+    else maybeIndex
+  }
+
+  // This method is unsafe. It's up to the selectOverview method to handle each index OOB error for
+  // each indivdual strategy
+  private def selectIndexByProximity(overviewCS: List[CellSize], desiredCS: CellSize, proximityThreshold: Double): Int =
+    overviewCS.search(desiredCS) match {
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala:68]: I guess this could be replaed with a [foldM](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Foldable.scala#L384) function

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 12]
```diff
@@ -16,20 +16,97 @@
...
+  */
 sealed trait OverviewStrategy
+
+object OverviewStrategy {
+  def DEFAULT = AutoHigherResolution
+
+  /**
+    * Select appropriate overview given the strategy.
+    *
+    * WARN: this function assumes that CellSizes are sorted. It interprets idx 0 as the position with the highest CellSize.
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala:35]: Taking into the account that this is true, usage of the search function in the `selectIndexByProximity` function makes it really hard to interpret.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 13]
```diff
@@ -16,20 +16,97 @@
...
+        overviewIdx
+      case Auto(n) =>
+        selectIndexByProximity(overviewCS, desiredCS, 0.5) + n
+      case Base =>
+        overviewCS.indexOf(overviewCS.min)
+      case AutoHigherResolution =>
+        val idx = selectIndexByProximity(overviewCS, desiredCS, 1.0)
+        // AutoHigherResolution defaults to the closest level
+        // idx > overviewCS.size means, that idx = overviewCS.size (last idx + 1)
+        if (idx > overviewCS.size) idx - 1 else idx
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala:60]: We need to know where is the highest resolution to interpret the index the `selectIndexByProximity` function. If the input list is sorted, `idx > overviewCS.size` means the lower resolution. In case it is reversed, it means the higher resolution. If the list is not sorted, this index makes no sense for its interpretation.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 14]
```diff
@@ -16,20 +16,122 @@
...
+  
+  /**
+    * This method is unsafe. It's up to the selectOverview method to handle each index OOB error.
+    * @param overviewCS        a sorted list of resolutions, otherwise it is not guaranteed that it would work with all the input strategies.
+    * @param desiredCS          cellSize that would be searched  
+    * @param proximityThreshold threshold to defined the search proximity
+    * @return                   index of the closest cellSize. Returns -1 in case nothing was found or the input list was not sorted.  
+    */
+  private def selectIndexByProximity(overviewCS: List[CellSize], desiredCS: CellSize, proximityThreshold: Double): Int =
+    overviewCS.zipWithIndex.foldLeftM(Option.empty[(CellSize, Int)]) { case (acc, r @ (rightCZ, _)) =>
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala:87]: I am not sure that with folding it is much easier to read, however it is more explicit about sorting.

File: raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala [hunk 15]
```diff
@@ -16,20 +16,122 @@
...
+      acc match {
+        case l @ Some((leftCZ, _)) =>
+          val proportion = 1 - (rightCZ.resolution - desiredCS.resolution) / (rightCZ.resolution - leftCZ.resolution)
+
+          // if the rightCZ > than the leftCZ it means that the list is not sorted
+          // - negative if rightCZ < leftCZ
+          // - positive if rightCZ > leftCZ
+          // - zero otherwise (if rightCZ == leftCZ)
+          if (Ordering[CellSize].compare(rightCZ, leftCZ) < 0) {
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala:96]: short circuiting if the list is not sorted
