### PR TITLE
Test storage method for tiff writes

### LINKED ISSUE #3335: storageMethod in GeoTiffOptions for SingleBandTiff writing doesn't work
## Describe the bug

storageMethod in GeoTiffOptions for SingleBandGeoTiff writing doesn't work.

Attached [TIFF](https://dsafsadfafdsa.s3.ap-northeast-2.amazonaws.com/OUTPUT.tif)
When writing out a singleBandTiff using `GeoTiffOptions`  `storageMethod` couldn't generate a will tiled Tiff,still a striped one. While it works well for MultibandGeoTiff.
## To Reproduce

Provide as able:

- Steps to reproduce the behavior
- Code example
`MultibandGeoTiff(MultibandTile(tile_ndvi), extent, crs,
      GeoTiffOptions.DEFAULT.copy(
        storageMethod = Tiled(256, 256) 
        compression = Deflate 
      )).write("xx")`.   // generate a well tiled tif

`
  SinglebandGeoTiff(tile_ndvi, extent, crs,
      mtb_tiff.tags,
      GeoTiffOptions.DEFAULT.copy(
        storageMethod = Tiled(256, 256),
        compression = Deflate
      )).write("xx).  //still write out a striped tif
`
- Inputs
- Actual output
- Expected output

## Environment

- Java version:1.8
- Scala version:2.11.12
- GeoTrellis version: 3.3.1

### PR DESCRIPTION
**Pull request by moradology**
# Overview

Add tests to demonstrate respect for `StorageMethod` on `GeoTiff` write options.

## Checklist

- [x] Unit tests added for bug-fix or new feature

## Notes

Couldn't reproduce bug; simply adding a test to ensure no regression from here

Closes #3335

### CODE REVIEW

File: raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala [hunk 1]
```diff
@@ -54,6 +54,52 @@ class GeoTiffWriterSpec extends AnyFunSpec with Matchers with BeforeAndAfterAll
       actual should be (expected)
     }
 
+    it("should write GeoTiff with correct layout (tiled vs striped)") {
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala:57]: I feel like we could split tests into two: 

* Tiled => Striped conversion (the source is read from a tiled TIFF file; let's create this one via GDAL, so it's a given input)
* Striped => Tiled conversions (the source is read from a striped TIFF file; let's create this one via GDAL, so it's a given input)

For two categories of Tiffs:

* Singleband
* Multiband 

Total +4 separate tests (a bit easier to read, and less complex in general).

File: raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala [hunk 2]
```diff
@@ -54,6 +54,52 @@ class GeoTiffWriterSpec extends AnyFunSpec with Matchers with BeforeAndAfterAll
...
+
+      val mbGeoTiffStriped = MultibandGeoTiff(
+        mbtile, Extent(0, 0, 1, 1), LatLng, Tags.empty,
+        GeoTiffOptions.DEFAULT.copy(storageMethod=Striped())
+      )
+      val mbtempStriped = File.createTempFile("geotiff-writer-striped-mb", ".tif")
+      addToPurge(mbtempStriped.getPath)
+      GeoTiffWriter.write(mbGeoTiffStriped, mbtempStriped.getPath)
+      val mbactualStriped = MultibandGeoTiff(mbtempStriped.getPath)
+      assert(mbactualStriped.options.storageMethod.isInstanceOf[Striped])
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala:80]: Hm, lets follow the test suite style, instead of assers we can use scalatest matchers, smth like:

```scala
mbactualStriped.options.storageMethod shouldBe a [Striped]
```

**Review by pomadchin — CHANGES_REQUESTED** [review]
:+1: noice, thank you! Let's clean up tests a bit though?

**Comment by pomadchin** [comment]
@moradology I feel like [0740b95](https://github.com/locationtech/geotrellis/pull/3481/commits/0740b95f4a2208604ae5bed1a3c705f65cad3327) belongs to a different PR :D

**Comment by moradology** [comment]
A comedy of errors 😭

**Review by pomadchin — APPROVED** [review]
🔥
