### PR TITLE
#3144: MinResample / MaxResample: preserve NODATA correctly for double cell …

### LINKED ISSUE #3144: Pyramid.fromLayerRDD fails to respect NODATA values with ResampleMethods.Max
I have a `TileLayerRDD[SpatialKey]` and am generating an image pyramid with the following code snippet:
```scala
def savePng(
    layer: TileLayerRDD[SpatialKey],
    colorMap: ColorMap,
    outputPath: String
  ): Unit = {
    implicit val sc: SparkContext = layer.sparkContext

    val (baseZoom, baseLayer) = layer.reproject(ZoomedLayoutScheme(WebMercator, 256))
    val pyramid = Pyramid.fromLayerRDD(
      baseLayer,
      Some(baseZoom),
      Some(0),
      resampleMethod = ResampleMethods.Max
    )

    pyramid.levels.foreach { case (zoom, tileRdd) =>
      val imageRdd: RDD[(SpatialKey, Array[Byte])] =
        tileRdd.mapValues(_.renderPng(colorMap).bytes)

      val keyToPath = { k: SpatialKey => s"${outputPath}/${zoom}/${k.col}/${k.row}.png" }
      if (outputPath.startsWith("s3")) {
        SaveToS3(imageRdd, keyToPath, { request =>
          request.toBuilder.acl(ObjectCannedACL.PUBLIC_READ).build()
        })
      } else {
        SaveToHadoop(imageRdd, keyToPath)
      }
    }
  }
```

When this layer is generated and displayed on a map, all zoom levels past the base zoom level replace nodata values with the value of the first color ramp:
https://tilejson.io/g/90e81c9fd2ed500609829d5df5af93dc/view

When I use the default ResampleMethod.Average this does not occur. It appears that [MaxResample handles NoData values correctly](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala#L38)

### PR DESCRIPTION
**Pull request by kervel**
# Overview

The current code set NODATA for nodata cells, but NODATA is only valid for Int cell types. Double.NaN or doubleNODATA should be used for double cells
See #3144

## Checklist

- [x] [docs/CHANGELOG.rst](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary
- [ ] [Module Hierarcy](https://github.com/locationtech/geotrellis/blob/master/docs/guide/module-hierarchy.rst) updated, if necessary
- [ ] `docs` guides update, if necessary
- [ ] New user API has useful Scaladoc strings
- [ ] Unit tests added for bug-fix or new feature

## Demo

Optional. Screenshots/REPL

## Notes

Closes #3144

### CODE REVIEW

File: raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala [hunk 1]
```diff
@@ -40,7 +40,7 @@ class MaxResample(tile: Tile, extent: Extent, targetCS: CellSize)
       // Double.NaN would *always* be max
       if (isData(v)) math.max(currentMax, v) else currentMax
     }
-    if (doubleMax == Double.MinValue) NODATA else doubleMax
+    if (doubleMax == Double.MinValue) doubleNODATA else doubleMax
```
Comment (metasim) [inline raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala]: 😨

**Comment by kervel** [comment]
(oops i broke the tests, now the tests are fixed)

File: raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala (hunk 1 above)
Comment (kervel) [reply raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala]: not okay ?
