### PR TITLE
ArrayTile Equality Bug

### LINKED ISSUE #2869: ArrayTile equality is invalid
Equals test between `ArrayTile`s doesn't consider `CellType`, and only compares integral representation.

Not sure if this extends beyond `ArrayTile`s.

```scala
scala> val t1 = ArrayTile(Array(1, 2, 3, 4), 2, 2)
t1: geotrellis.raster.IntConstantNoDataArrayTile = IntConstantNoDataArrayTile([I@1b69f8dd,2,2)

scala> val t2 = ArrayTile(Array(1.1, 2.2, 3.3, 4.4), 2, 2)
t2: geotrellis.raster.DoubleConstantNoDataArrayTile = DoubleConstantNoDataArrayTile([D@43fb8901,2,2)

scala> t1 == t2
res0: Boolean = true
```

Tested against GT 2.1.0.

### PR DESCRIPTION
**Pull request by jbouffard**
## Overview

This fixes an equality bug in `ArrayTile` where `cols`, `rows`, and `cellType` of the two tiles were not taken into account. They now are.

### Checklist

- [x] `docs/CHANGELOG.rst` updated, if necessary
- [x] Unit tests added for bug-fix or new feature

Closes #2869

### CODE REVIEW

**Comment by jbouffard** [comment]
@pomadchin It looks like it's failing for me locally too... I'm not sure what's up with that.

File: raster/src/main/scala/geotrellis/raster/ArrayTile.scala [hunk 1]
```diff
@@ -296,15 +296,23 @@ trait ArrayTile extends Tile with Serializable {
...
+
       var i = 0
-      while (i < len) {
-        if (apply(i) != r(i)) return false
-        i += 1
-      }
+
+      if (cellType.isFloatingPoint)
+        while (i < size) {
+          if (applyDouble(i) != tile.applyDouble(i)) return false
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/ArrayTile.scala]: Bad doubles comparison, use `java.lang.Double.equals`

Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/ArrayTile.scala]: Doubles can compare `NaN`s incorrectly here.
