### PR TITLE
WKTParser extension support

### LINKED ISSUE #3241: WKT Proj4 Extension support
WKT strings can be of the following shape:

```
PROJCS[
  "WGS 84 / Pseudo-Mercator",
  GEOGCS["WGS 84",
    DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]], 
    UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]
  ],
  PROJECTION["Mercator_1SP"],
  PARAMETER["central_meridian",0],
  PARAMETER["scale_factor",1],
  PARAMETER["false_easting",0],
  PARAMETER["false_northing",0],
  UNIT["metre",1,AUTHORITY["EPSG","9001"]],
  AXIS["Easting",EAST],
  AXIS["Northing",NORTH],
  EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"],
  AUTHORITY["EPSG","3857"]
]
```

Right now parsing of such a string is not supported (parser will throw an exception, trying to parse `EXTENSION`).

The task is to add into parser `EXTENSIONS` support and to use PROJ4 Extension to convert WKT string into CRS by parsing the proj4 string from the Extentions field.

### PR DESCRIPTION
**Pull request by pomadchin**
# Overview

## Checklist

- [x] [docs/CHANGELOG.rst](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary
- [x] Unit tests added for bug-fix or new feature

Closes #3241

### CODE REVIEW

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala [hunk 1]
```diff
@@ -44,12 +44,23 @@ case class Projection(name: String, authority: Option[Authority])
...
-case class CompDCS(name: String, head: Any, tail: Any, authority: Option[Authority]) extends WktCS
\ No newline at end of file
+case class CompDCS(name: String, head: Any, tail: Any, authority: Option[Authority]) extends WktCS
+
+sealed trait Extension {
+  def name: String
+  def value: String
+}
+
+case class ExtensionProj4(value: String) extends Extension {
```
Comment (pomadchin) [inline proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala:62]: I'm still wondering was it a good idea to make it a part of the parsing DSL or not.

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala [hunk 2]
```diff
@@ -52,28 +52,35 @@ object WKT {
...
-    parsed.find{
-      case (_, wkt) => wkt == wktParsed
-    }.map(_._1)
+    val db = parsed.find { case (_, wkt) => wkt == wktParsed }.map(_._1)
+    if(db.nonEmpty) db
+    else
+      wktParsed match {
+        case wkt: ProjCS =>
+          wkt.extension.flatMap {
+            case ExtensionProj4(proj4String) =>
```
Comment (pomadchin) [inline proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala:61]: That is why it is convinient to have `ExtensionProj4`

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala (hunk 1 above)
Comment (CloudNiner) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala:62]: Can you describe why or why not? I think I'm lacking some project context to know more.

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala (hunk 2 above)
Comment (CloudNiner) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala:61]: You're just saying its convenient to be able to `match` on the ExtensionProj4 case class right?

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WKTParser.scala [hunk 3]
```diff
@@ -37,83 +37,88 @@ object WKTParser extends RegexParsers {
...
   }
 
   def coordinateSys: Parser[Any] = geogcs | geoccs | projcs | vertcs | compdcs | localcs
 
   def compdcs: Parser[CompDCS] = """COMPD_CS[""" ~ string ~ comma ~ coordinateSys ~ comma ~ coordinateSys ~ comma.? ~ authority.? ~ """]""" map {
-    case _ ~ name ~ _ ~ head ~ _ ~ tail ~ _ ~ auth ~ _ => new CompDCS(name, head, tail, auth)
+    case _ ~ name ~ _ ~ head ~ _ ~ tail ~ _ ~ auth ~ _ => CompDCS(name, head, tail, auth)
   }
 
+def extension: Parser[Extension] = """EXTENSION[""" ~ string ~ comma ~ string ~ """]""" map {
```
Comment (CloudNiner) [inline proj4/src/main/scala/geotrellis/proj4/io/wkt/WKTParser.scala:117]: Indentation is off here I think.

File: proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala [hunk 4]
```diff
@@ -658,4 +659,52 @@ class WKTParserTest extends FunSpec {
...
+                             |AXIS["Easting",EAST],
+                             |AXIS["Northing",NORTH],
+                             |EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"],
+                             |AUTHORITY["EPSG","3857"]]""".stripMargin)
+
+    // single line equivalent
+    val single = WKTParser("""PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"],AUTHORITY["EPSG","3857"]]""")
+
+    assert(strip == single)
```
Comment (CloudNiner) [inline proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala:684]: Hmm what am I missing here? This test is just checking to see if two strings that are the same are parsing the same, but not specifically checking whether or not the extension was properly parsed?

File: proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala [hunk 5]
```diff
@@ -63,4 +64,12 @@ class WKTTest extends FunSpec {
     val epsgCodeOfWKT = WKT.getEpsgStringCode("PROJCS[\"WGS 84 / Pseudo-Mercator\", GEOGCS[\"WGS 84\", DATUM[\"World Geodetic System 1984\", SPHEROID[\"WGS 84\", 6378137.0, 298.257223563, AUTHORITY[\"EPSG\",\"7030\"]], AUTHORITY[\"EPSG\",\"6326\"]], PRIMEM[\"Greenwich\", 0.0, AUTHORITY[\"EPSG\",\"8901\"]], UNIT[\"degree\", 0.017453292519943295], AXIS[\"Geodetic longitude\", EAST], AXIS[\"Geodetic latitude\", NORTH], AUTHORITY[\"EPSG\",\"4326\"]], PROJECTION[\"Popular Visualisation Pseudo Mercator\", AUTHORITY[\"EPSG\",\"1024\"]], PARAMETER[\"semi_minor\", 6378137.0], PARAMETER[\"latitude_of_origin\", 0.0], PARAMETER[\"central_meridian\", 0.0], PARAMETER[\"scale_factor\", 1.0], PARAMETER[\"false_easting\", 0.0], PARAMETER[\"false_northing\", 0.0], UNIT[\"m\", 1.0], AXIS[\"Easting\", EAST], AXIS[\"Northing\", NORTH], AUTHORITY[\"EPSG\",\"3857\"]]").get
     assert(comparisonCode == epsgCodeOfWKT)
   }
+
+  // TODO: fix proj4j, it should be identify this projection as EPSG:3857
```
Comment (CloudNiner) [inline proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala:68]: Wouldn't this code block be better as a new issue, either in this repo or in upstream proj4j if we can verify that there is in fact a bug in that code?

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala (hunk 2 above)
Comment (pomadchin) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala:61]: Yep!

File: proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala (hunk 4 above)
Comment (pomadchin) [reply proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala:684]: @CloudNiner yea just checks the multistring parsing :D I can make it more smart, thanks :+1:

File: proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala (hunk 5 above)
Comment (pomadchin) [reply proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala]: https://github.com/locationtech/proj4j/issues/61

File: proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala (hunk 1 above)
Comment (pomadchin) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala:62]: https://github.com/locationtech/geotrellis/pull/3244#discussion_r427971659

Comment (pomadchin) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala:62]: I'm also wondering, mb there is a better for Extention that is just anything and not Proj4?

Comment (CloudNiner) [reply proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala:62]: Including as part of the DSL seems fine, its what we do for all the other things we need to parse, so that feels consistent at least. 

IDK about better names. All the other parsers match the names being parsed out, like `Parser[GeocCS]` looks for `GEOCCS[]`. So what's here is consistent with the current naming convention. Kinda annoying that its such a generic word that could be confused in other contexts, but it seems pretty well isolated here at first glance, so :shrug:
