### PR TITLE
Fix MosaicRasterSource.tileToLayout behavior

### LINKED ISSUE #3253: TileToLayout a MosaicRasterSource issue
Tiling to layout a `MosaicRasterSource` with more than a single `RasterSource` leads to incorrect reads.

[Link to a unit test that reproduces the bad behavior](https://github.com/pomadchin/geotrellis/commit/597466aca2e20d008cc5ffcb433c70a6112a7d14#diff-efc4b4c63eea4456ec6ea3f52cdd52e0R212-R232).

### PR DESCRIPTION
**Pull request by pomadchin**
# Overview

`MosaicRasterSource.tileToLayout` with more than a single `RasterSource` leads to incorrect reads.

## Checklist

- [x] [./CHANGELOG.md](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary. Link to the issue if closed, otherwise the PR.
- [x] Unit tests added for bug-fix or new feature

Closes #3253

### CODE REVIEW

File: raster/src/main/scala/geotrellis/raster/MosaicRasterSource.scala [hunk 1]
```diff
@@ -93,7 +93,29 @@ abstract class MosaicRasterSource extends RasterSource {
...
-    val rasters = sources map { _.read(bounds, bands) }
+    /** The passed bounds are relative to the [[MosaicRasterSource]] bounds.
+      * However, each [[RasterSource]] has its own [[GridBounds]].
+      * Before passing [[GridBounds]] into each underlying [[RasterSource]]
+      * we need to map them into the each [[RasterSource]] relative grid space.
+      *
+      * This is done by calculating the relative offset using each [[RasterSource]]
+      * underlying [[Extent]].
+      */
+    def gridBoundsRelative(gb: GridBounds[Long], extent: Extent): GridBounds[Long] = {
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/MosaicRasterSource.scala:104]: would the `gridBoundsShift` name be better?

File: layer/src/test/scala/geotrellis/layer/LayoutTileSourceSpec.scala [hunk 2]
```diff
@@ -268,13 +271,54 @@ class LayoutTileSourceSpec extends AnyFunSpec with RasterMatchers {
...
+        ones.sum shouldBe arr.size
       }
 
       neighborhood map {
         case (x, y) => checkExtent(x, y, rs)
       }
     }
+
+    // https://github.com/locationtech/geotrellis/issues/3253
+    it("MosaicRasterSource should be properly tiled to layout") {
```
Comment (pomadchin) [inline layer/src/test/scala/geotrellis/layer/LayoutTileSourceSpec.scala:284]: The idea of the test, is to prove that the read by extent behaves the same way as the read by keys (by bounds).

File: layer/src/main/scala/geotrellis/layer/LayoutTileSource.scala [hunk 3]
```diff
@@ -82,10 +82,24 @@ class LayoutTileSource[K: SpatialComponent](
...
+          * However, if the source is a [[MosaicRasterSource]], offsets are still relative to the underlying [[RasterSource]].
+          * In this case it is possible to compute offsets through the returned extent.
+          */
+
+        // the actual returned extent
+        val actualExtent = raster.extent
+        // expected extent
+        val expectedRasterExtent = RasterExtent(layout.mapTransform(spatialComponent), layout.tileCols, layout.tileRows)
+
+        val colOffset = GridExtent.floorWithTolerance((actualExtent.xmin - expectedRasterExtent.extent.xmin) / expectedRasterExtent.cellwidth).toLong
```
Comment (echeipesh) [inline layer/src/main/scala/geotrellis/layer/LayoutTileSource.scala:100]: This is actually mapToGrid call ?
