### PR TITLE
Fix Encoder[GeometryCollection]

### LINKED ISSUE #3167: GeometryCollection encoding issue
The following code
```
val p = Point(1, 1)
println(GeometryCollection(multiPoints = Seq(MultiPoint(p, p))).toGeoJson)
```
prints
```
{
  "type" : "GeometryCollection",
  "geometries" : [
    {"type" : "MultiPoint", "coordinates" : [[1.0, 1.0], [1.0, 1.0]]},
    {"type" : "GeometryCollection", "geometries" : [
      {"type" : "Point", "coordinates" : [1.0, 1.0]},
      {"type" : "Point", "coordinates" : [1.0, 1.0]}
    ]}
  ]
}
```
The same duplication happens with `MultiPolygons` and `MultiLines` when nested into `GeometryCollection`. It appears that this is because a `MultiPoint` IS a `GeometryCollection`, so the `Encoder` retrieves it two times - first by `getAll[MultiPoint]`, then by `getAll[GeometryCollection]`.

### PR DESCRIPTION
**Pull request by agrian-joel**
# Overview
Encoding a GeometryCollection with a Multipolygon/MultiPoint/MultiLineString should serialize those geometries once

Current behavior encodes them in geometries as both `type: MultiX` and `type: GeometryCollection`

## Checklist

- [X] [./CHANGELOG.md](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary. Link to the issue if closed, otherwise the PR.
- [X] Unit tests added for bug-fix or new feature

Closes #3167

### CODE REVIEW

**Comment by pomadchin** [comment]
Hi @agrian-joel thanks a lot for your first contribution! I'll review it a bit later.

File: vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala [hunk 1]
```diff
@@ -176,15 +176,16 @@ trait GeometryFormats {
...
-          obj.getAll[Point].map(_.asJson),
-          obj.getAll[LineString].map(_.asJson),
-          obj.getAll[Polygon].map(_.asJson),
-          obj.getAll[MultiPoint].map(_.asJson),
-          obj.getAll[MultiLineString].map(_.asJson),
-          obj.getAll[MultiPolygon].map(_.asJson),
-          obj.getAll[GeometryCollection].map(_.asJson)
-        ).flatten.asJson
+        "geometries" -> 
+          obj.geometries.map({
```
Comment (pomadchin) [inline vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala:180]: In order not to throw in case of the type mismatch, it is possible to use the `collect` function instead of `map` here (see the comment https://github.com/locationtech/geotrellis/pull/3288#discussion_r483846948)

**Review by pomadchin — APPROVED** [review]
Thanks!
