### PR TITLE
ConstantTile to ArrayTile CellType Fix

### LINKED ISSUE #2493: Conversion from ConstantTile to ArrayTile doesn't preserve NoData.
Calling `toArrayTile` on a `ConstantTile` should not change the `CellType`.

```scala
scala> val t3 = ByteConstantTile(7, 3, 3, ByteCellType)
t3: geotrellis.raster.ByteConstantTile = ByteConstantTile(7,3,3,int8raw)

scala> t3.toArrayTile.cellType
res15: geotrellis.raster.CellType = int8

scala> val t4 = ByteConstantTile(7, 3, 3, ByteUserDefinedNoDataCellType(32))
t4: geotrellis.raster.ByteConstantTile = ByteConstantTile(7,3,3,int8ud32)

scala> t4.toArrayTile.cellType
res16: geotrellis.raster.CellType = int8
```

### PR DESCRIPTION
**Pull request by jbouffard**
This PR makes it so that the `CellType` is retained when converting a `ConstantTile` to an `ArrayTile`.

This PR resolves #2493

### CODE REVIEW

File: raster/src/main/scala/geotrellis/raster/ConstantTile.scala [hunk 1]
```diff
@@ -390,7 +390,7 @@ case class UByteConstantTile(v: Byte, cols: Int, rows: Int,
     *
     * @return  The MutableArrayTile
     */
-  def mutable(): MutableArrayTile = ByteArrayTile.fill(v, cols, rows)
+  def mutable(): MutableArrayTile = UByteArrayTile.fill(v, cols, rows, cellType)
```
Comment (aheyne) [inline raster/src/main/scala/geotrellis/raster/ConstantTile.scala]: Good catch!

Comment (jbouffard) [reply raster/src/main/scala/geotrellis/raster/ConstantTile.scala]: Thanks! I'm a little surprised that wasn't caught sooner.
