### PR TITLE
SpatialIndex use of Traversable

### LINKED ISSUE #3349: SpatialIndex does not compile in Scala 2.13 because of Traversable changes
## Describe the bug

SpatialIndex does not compile in Scala 2.13 because Traversable requires method `iterator` to be implemented.

## To Reproduce

Compile `vector` using the 2.13-enabled branch from this PR https://github.com/locationtech/geotrellis/pull/3346 

## Expected behavior

Compiles with out error.

## Screenshots

n/a

## Environment

- Java version:
- Scala version:
- GeoTrellis version:

### PR DESCRIPTION
**Pull request by philvarner**
Signed-off-by: philvarner <philvarner@gmail.com>

# Overview

In `SpatialIndex`, the method `traversePointsInExtent` returns a Traversable. Traversable is being phased out in favor of Iterable. This method is only used within GT in the `pointsInExtent` method and has no direct unit tests, so it probably should have been a protected/private method. 

This change does the following:

1. Adds `pointsInExtentAsIterable` (named so as not to conflict with `pointsInExtent(...): Vector`) that returns an Iterable and uses this method in `pointsInExtent`
2. deprecates `traversePointsInExtent` in favor of `pointsInExtentAsIterable` (named so as not to conflict with `pointsInExtent(...): Vector`)
3. implements method `iterator` in Traversable as required by 2.13. This is backwards-compatible with 2.11 and 2.12. 

## Checklist

- [X] [./CHANGELOG.md](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary. Link to the issue if closed, otherwise the PR.
- [ ] n/a [Module Hierarchy](https://github.com/locationtech/geotrellis/blob/master/docs/guide/module-hierarchy.rst) updated, if necessary
- [ ] n/a `docs` guides update, if necessary
- [ ] New user API has useful Scaladoc strings
- [ ] Unit tests added for bug-fix or new feature

## Demo

none

## Notes

Closes #3349

### CODE REVIEW

File: vector/src/main/scala/geotrellis/vector/SpatialIndex.scala [hunk 1]
```diff
@@ -81,10 +87,20 @@ class SpatialIndex[T](val measure: Measure = Measure.Euclidean) extends Serializ
         }
         rtree.query(extent.jtsEnvelope, visitor)
       }
+
+      // Traversable implementations must override iterator in 2.13
+      def iterator: Iterator[T] =
+        rtree.query(extent.jtsEnvelope).asScala.map(_.asInstanceOf[T]).iterator
+    }
+
+  def pointsInExtentAsIterable(extent: Extent): Iterable[T] =
```
Comment (pomadchin) [inline vector/src/main/scala/geotrellis/vector/SpatialIndex.scala:96]: Tbh I like this function naming much more than the `{traverse|iterate}PointsInExtent`. :+1:

**Review by pomadchin — APPROVED** [review]
:+1: That's a very nice compatibility solution.
