### PR TITLE
Make all tests Java Serialization compatible

### LINKED ISSUE #2721: 2.0.0-RC1 is no longer compatible with Java Serialization
As of the RC1 release, Python tests in RasterFrames that used to work in 1.2.1 now fail. It appears to be related to Kryo serialization, which the Python tests never bothered with (the Scala ones use `spark-testkit`, which does).

If you run GT tests with `GEOTRELLIS_USE_JAVA_SER=true` set in the environment, which disables `KryoSerialization`, the following tests will fail:

* `geotrellis.spark.render.SpatialTileRDDRenderMethodsSpec`
* `geotrellis.spark.reproject.TileRDDReprojectSpec`
* `geotrellis.spark.io.slippy.HadoopSlippyTileWriterSpec`
* `geotrellis.spark.costdistance.RDDCostDistanceMethodsSpec`
* `geotrellis.spark.distance.EuclideanDistanceSpec`
* `geotrellis.spark.costdistance.IterativeCostDistanceSpec`

For example, run:

```console
GEOTRELLIS_USE_JAVA_SER=true sbt "spark/testOnly geotrellis.spark.reproject.TileRDDReprojectSpec"
```

Even though Kryo is highly recommended, it would be nice if we can still be compatible with Java Serialization, as it serves as a smoke tests for unintended object serialization. Therefore, I think we should find out whatever changed to break the serialization. So far they all appear to be related to GeoTIFF reading.

## GeoTrellis Backtrace
```java
   org.apache.spark.SparkException: Job aborted due to stage failure: Failed to serialize task 174, not attempting to retry it. Exception during serialization: java.io.NotSerializableException: geotrellis.raster.io.geotiff.Float32BandType$
 	- field (class "geotrellis.raster.io.geotiff.Float32GeoTiffTile", name: "bandType", type: "class geotrellis.raster.io.geotiff.Float32BandType$")
 	- object (class "geotrellis.raster.io.geotiff.Float32GeoTiffTile", geotrellis.raster.io.geotiff.Float32GeoTiffTile@7c8a5bb5)
 	- field (class "scala.Tuple2", name: "_2", type: "class java.lang.Object")
 	- object (class "scala.Tuple2", (ProjectedExtent(Extent(630000.0, 225940.0, 632560.0, 228500.0),lcc-CS),geotrellis.raster.io.geotiff.Float32GeoTiffTile@7c8a5bb5))
 	- element of array (index: 0)
 	- array (class "[Lscala.Tuple2;", size: 1)
 	- field (class "scala.collection.mutable.WrappedArray$ofRef", name: "array", type: "class [Ljava.lang.Object;")
 	- object (class "scala.collection.mutable.WrappedArray$ofRef", WrappedArray((ProjectedExtent(Extent(630000.0, 225940.0, 632560.0, 228500.0),lcc-CS),geotrellis.raster.io.geotiff.Float32GeoTiffTile@7c8a5bb5)))
 	- field (class "org.apache.spark.rdd.ParallelCollectionPartition", name: "values", type: "interface scala.collection.Seq")
 	- custom writeObject data (class "org.apache.spark.rdd.ParallelCollectionPartition")
 	- object (class "org.apache.spark.rdd.ParallelCollectionPartition", org.apache.spark.rdd.ParallelCollectionPartition@1245)
 	- field (class "org.apache.spark.scheduler.ResultTask", name: "partition", type: "interface org.apache.spark.Partition")
 	- root object (class "org.apache.spark.scheduler.ResultTask", ResultTask(44, 3))
   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1587)
   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1586)
   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1586)
   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
   at scala.Option.foreach(Option.scala:257)
   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1820)
   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
   at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
   at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2124)
   at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1029)
   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
   at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
   at org.apache.spark.rdd.RDD.reduce(RDD.scala:1011)
   at geotrellis.spark.TileLayerMetadata$.collectMetadataWithCRS(TileLayerMetadata.scala:153)
   at geotrellis.spark.TileLayerMetadata$.fromRdd(TileLayerMetadata.scala:243)
   at geotrellis.spark.Implicits$withCollectMetadataMethods.collectMetadata(Implicits.scala:256)
   at geotrellis.spark.reproject.TileRDDReprojectSpec$$anonfun$2$$anonfun$apply$mcV$sp$11.apply(TileRDDReprojectSpec.scala:253)
   at geotrellis.spark.reproject.TileRDDReprojectSpec$$anonfun$2$$anonfun$apply$mcV$sp$11.apply(TileRDDReprojectSpec.scala:245)
   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
   at org.scalatest.Transformer.apply(Transformer.scala:22)
   at org.scalatest.Transformer.apply(Transformer.scala:20)
   at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
   at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
   at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:451)
   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
   at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:464)
   at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
   at scala.collection.immutable.List.foreach(List.scala:392)
   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
   at scala.collection.immutable.List.foreach(List.scala:392)
   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
   at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
   at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
   at org.scalatest.Suite$class.run(Suite.scala:1147)
   at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
   at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:501)
   at geotrellis.spark.reproject.TileRDDReprojectSpec.org$scalatest$BeforeAndAfterAll$$super$run(TileRDDReprojectSpec.scala:37)
   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
   at geotrellis.spark.reproject.TileRDDReprojectSpec.run(TileRDDReprojectSpec.scala:37)
   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
   at sbt.TestRunner.runTest$1(TestFramework.scala:106)
   at sbt.TestRunner.run(TestFramework.scala:117)
   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
   at sbt.TestFunction.apply(TestFramework.scala:271)
   at sbt.Tests$.processRunnable$1(Tests.scala:307)
   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:313)
   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
   at sbt.std.Transform$$anon$4.work(System.scala:66)
   at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
   at sbt.Execute.work(Execute.scala:272)
   at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
```

## RasterFrames Backtrace

```java
py4j.protocol.Py4JJavaError: An error occurred while calling o91.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Failed to serialize task 15, not attempting to retry it. Exception during serialization: java.io.NotSerializableException: geotrellis.raster.io.geotiff.ArraySegmentBytes
Serialization stack:
	- object not serializable (class: geotrellis.raster.io.geotiff.ArraySegmentBytes, value: ArraySegmentBytes([B@9458bd7, ... [B@60db128f))
   	- field (class: geotrellis.raster.io.geotiff.GeoTiffMultibandTile, name: segmentBytes, type: interface geotrellis.raster.io.geotiff.SegmentBytes)
   	- object (class geotrellis.raster.io.geotiff.UInt16GeoTiffMultibandTile, geotrellis.raster.io.geotiff.UInt16GeoTiffMultibandTile@1db904ce)
   	- field (class: scala.Tuple2, name: _2, type: class java.lang.Object)
   	- object (class scala.Tuple2, (ProjectedExtent(Extent(431902.5, 4313647.5, 443512.5, 4321147.5),EPSG:32616),geotrellis.raster.io.geotiff.UInt16GeoTiffMultibandTile@1db904ce))
   	- element of array (index: 0)
   	- array (class [Lscala.Tuple2;, size 1)
   	- field (class: scala.collection.mutable.WrappedArray$ofRef, name: array, type: class [Ljava.lang.Object;)
   	- object (class scala.collection.mutable.WrappedArray$ofRef, WrappedArray((ProjectedExtent(Extent(431902.5, 4313647.5, 443512.5, 4321147.5),EPSG:32616),geotrellis.raster.io.geotiff.UInt16GeoTiffMultibandTile@1db904ce)))
   	- writeObject data (class: org.apache.spark.rdd.ParallelCollectionPartition)
   	- object (class org.apache.spark.rdd.ParallelCollectionPartition, org.apache.spark.rdd.ParallelCollectionPartition@7e0)
   	- field (class: org.apache.spark.scheduler.ShuffleMapTask, name: partition, type: interface org.apache.spark.Partition)
   	- object (class org.apache.spark.scheduler.ShuffleMapTask, ShuffleMapTask(2, 7))
   	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
   	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
   	at scala.Option.foreach(Option.scala:257)
   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1928)
   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1941)
   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1954)
   	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:333)
   	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
   	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2386)
   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
   	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2788)
   	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2385)
   	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2392)
   	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2128)
   	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2127)
   	at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2818)
   	at org.apache.spark.sql.Dataset.head(Dataset.scala:2127)
   	at org.apache.spark.sql.Dataset.take(Dataset.scala:2342)
   	at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   	at java.lang.reflect.Method.invoke(Method.java:498)
   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
   	at py4j.Gateway.invoke(Gateway.java:280)
   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
   	at py4j.GatewayConnection.run(GatewayConnection.java:214)
   	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by pomadchin**
## Overview

The following tests were not passing with kryo serialization disabled. Only a part of them were related to a default tiff readers behavior change. 

- [x] geotrellis.spark.render.SpatialTileRDDRenderMethodsSpec (tiff reader change, explicit segments unpacking is required)
- [x] geotrellis.spark.reproject.TileRDDReprojectSpec (tiff reader change, explicit segments unpacking is required)
- [x] geotrellis.spark.io.slippy.HadoopSlippyTileWriterSpec (tiff reader change, explicit segments unpacking is required)
- [x] geotrellis.spark.costdistance.RDDCostDistanceMethodsSpec ([SI-7005](https://issues.scala-lang.org/browse/SI-7005))
- [x] geotrellis.spark.distance.EuclideanDistanceSpec (`IndexedPointSet` extends `Serializable`)
- [x] geotrellis.spark.costdistance.IterativeCostDistanceSpec ([SI-7005](https://issues.scala-lang.org/browse/SI-7005))
- [x] make GeoTiffTile types `Serializable`

Closes #2721

### CODE REVIEW

File: spark/src/main/scala/geotrellis/spark/io/RasterReader.scala [hunk 1]
```diff
@@ -64,13 +64,13 @@ object RasterReader {
     def readFully(byteReader: ByteReader, options: Options) = {
       val geotiff = SinglebandGeoTiff(byteReader)
       val raster: Raster[Tile] = geotiff.raster
-      (ProjectedExtent(raster.extent, options.crs.getOrElse(geotiff.crs)), raster.tile)
+      (ProjectedExtent(raster.extent, options.crs.getOrElse(geotiff.crs)), raster.tile.toArrayTile)
```
Comment (metasim) [inline spark/src/main/scala/geotrellis/spark/io/RasterReader.scala]: @pomadchin I'm curious; before these changes, were we benefitting from any lazy evaluation? If so, another option to making the classes Java serialization friendly would be to override the `writeObject` or `writeResolve` (I forget the difference) to implicitly do the `toArrayTile` part when needed.

Comment (pomadchin) [reply spark/src/main/scala/geotrellis/spark/io/RasterReader.scala]: it would be enough to extend serializable, not sure what would be the benefit of implementing these method(s).

**Comment by pomadchin** [comment]
So the problem problems was in `readSingleband(streaming = true, decompress = true)` here: https://github.com/locationtech/geotrellis/pull/2650/files#diff-7fd841ac3e435a690c3e16a2d50d0963L219

So by default you were reading it as decompressed and non streaming. We decided to change the default behavior to read tiffs as `compressed` and `streaming` and to remove that ambiguous `decompress` flag at all.

**Comment by metasim** [comment]
I should point out that my selection of the `compressed` and `streaming` tags was not informed, but just picking what looked like other uses were doing. So if there's something I should change at my end, let me know.

**Comment by metasim** [comment]
@pomadchin I just clicked "approve", but wonder if serialization will handle the lazy eval case? Or maybe I'm misunderstanding what we're going back and fort on.

**Comment by pomadchin** [comment]
@metasim yea should work, all `GeoTiffTile` types and `MultibandGeoTiffTile` types should work as expected. To check it revert changes in `geotrellis.spark.render.SpatialTileRDDRenderMethodsSpec` introduced by this PR, disable kryo and this test would work (it would handle `Float32GeoTiffTile` via Java ser fine).

**Comment by pomadchin** [comment]
It seems to me that it is our oversight that it was not serializable before
