### PR TITLE
Fix Tiled TIFF BitCellType Segments conversion

### LINKED ISSUE #3055: Error When Saving a COGLayer With a BitCellType
I'm currently trying to save an `RDD[(SpatialKey, MultibandTile)]` whose cells are in the `BitCellType` as a COG layer locally. However, this error occurs during the writing process:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at geotrellis.raster.io.geotiff.BitGeoTiffSegment.get(BitGeoTiffSegment.scala:49)
	at geotrellis.raster.io.geotiff.BitGeoTiffSegment.getInt(BitGeoTiffSegment.scala:36)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$geotrellis$raster$io$geotiff$GeoTiffMultibandTile$$burnPixelInterleave$1$1.apply(GeoTiffMultibandTile.scala:586)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$geotrellis$raster$io$geotiff$GeoTiffMultibandTile$$burnPixelInterleave$1$1.apply(GeoTiffMultibandTile.scala:568)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.geotrellis$raster$io$geotiff$GeoTiffMultibandTile$$burnPixelInterleave$1(GeoTiffMultibandTile.scala:568)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$12.apply(GeoTiffMultibandTile.scala:641)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$12.apply(GeoTiffMultibandTile.scala:640)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:331)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1334)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:514)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:502)
	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.toArrayTile(GeoTiffMultibandTile.scala:494)
	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:144)
	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:27)
	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:206)
	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:176)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After getting the first error, I looked through my code to ensure there wasn't anything I was doing to cause this issue. I was not able to find anything, though. I've tried writing the same data in a different `CellType`, and that was able to work; so it appears that the `BitCellType` is the issue.

I don't have an easy way to reproduce this error right now, but I should in the future, and I'll update this issue with those instructions when the time comes.

### PR DESCRIPTION
**Pull request by pomadchin**
## Overview

This PR fixes `GeoTIffTile` `CellType` conversion, in particular `GeoTiffSegment` `CellType` conversions. During the work on this fix, it became obvious that our TIFF API doesn't support a proper work with `striped` `BitTiffs` (this fact made this issue debugging a bit more tricky), that is why this PR at least covers `Tiled` tiffs support.

### Checklist

- [x] `docs/CHANGELOG.rst` updated, if necessary
- [x] Unit tests added for bug-fix or new feature

Fixes https://github.com/locationtech/geotrellis/issues/3055 

### Note

This issue indeed closes #3055 in any case, since COGs are Tiled TIFFs. If this PR won't cover `Striped` TIFFs support, I will create a separate issue to address it. This PR blocks a 3.0 release, a complete striped bit TIFFs support does not.

### CODE REVIEW

File: raster/src/test/scala/geotrellis/raster/io/geotiff/BitGeoTiffTileSpec.scala [hunk 1]
```diff
@@ -82,5 +76,22 @@ class BitGeoTiffTileSpec extends FunSpec
...
+    it("should convert tiled tiffs") {
+      val tiff = SinglebandGeoTiff(geoTiffPath("bilevel.tif"))
+      val tile = tiff.tile.toArrayTile() // .convert(BitCellType)
+
+      // check that it is possible to convert bit cellType to bit cellType
+      val tiffTile = tile.toGeoTiffTile(GeoTiffOptions.DEFAULT).convert(BitCellType)
+      assertEqual(tiffTile.toArrayTile(), tile.toArrayTile)
+
+      // check that it is possible to convert int cellType to bit cellType
+      // and that bitCellType conversion is idempotent
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/io/geotiff/BitGeoTiffTileSpec.scala]: This requires `idempotence` check, since it is the best way to prove that we're setting / unsetting and inverting bits correct to check that even / odd number of conversions would not affect the final result.
