### PR TITLE
Fixes #2792.

### LINKED ISSUE #2792: ArrayTile combine methods perform non-exhaustive matching
The following methods make incorrect assumptions about the `Tile` type-space. Because `Tile` inheritance is not restricted to the `geotrellis` namespace, type matching without a default handler should be considered a violation of the type contract.

https://github.com/locationtech/geotrellis/blob/bdc0ce22f657d87ef3f4ae9bdb953e7c9abd2564/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L224-L234

https://github.com/locationtech/geotrellis/blob/bdc0ce22f657d87ef3f4ae9bdb953e7c9abd2564/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L269-L278

I'm not sure I understand the purpose of these special cases (performance related?), but a default `case t: Tile => ???` should be implemented if possible.

### PR DESCRIPTION
**Pull request by metasim**
Also:
Adds new utility `DelegatingTile`.
Fixes compiler warning in CellTypeSpec.

Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>

- [ ] `docs/CHANGELOG.rst` updated, if necessary
- [ ] `docs` guides update, if necessary
- [ ] New user API has useful Scaladoc strings
- [X] Unit tests added for bug-fix or new feature

Closes #2792.

### CODE REVIEW

File: raster/src/main/scala/geotrellis/raster/DelegatingTile.scala [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+ */
+
+package geotrellis.raster
+
+/**
+ * A tile that wraps another tile. Originally intended for delayed reading, but useful in other special use cases.
+ *
+ * @since 8/22/18
+ */
+trait DelegatingTile extends Tile {
```
Comment (pomadchin) [inline raster/src/main/scala/geotrellis/raster/DelegatingTile.scala]: What's the use case of having it in the `gt` codebase? Just wondering. Mb it makes sense to add some doc strings for it? If it's only useful for tests it makes sense to move it into the test folder.

File: raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala [hunk 2]
```diff
@@ -164,5 +164,29 @@ class ArrayTileSpec extends FunSpec
...
+          override protected def delegate: Tile = DoubleConstantTile(0.0, 100, 100)
+        }
+
+        assertEqual(at.combineDouble(fauxTile)((z1, z2) => z1 + z2), at)
+      }
+    }
   }
 }
+
+object ArrayTileSpec {
```
[the remark this answers is not in the document]
Comment (metasim) [reply raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala]: Cruft... I'll remove. Originally had `DelegatingTile` in there

File: raster/src/main/scala/geotrellis/raster/DelegatingTile.scala (hunk 1 above)
Comment (metasim) [reply raster/src/main/scala/geotrellis/raster/DelegatingTile.scala]: I wrote it for RasterFrames core, and have found it useful for a few use cases and thought it was general purpose enough for cases where users' might want to have a `Tile` with slightly different behavior by overriding selected methods. If it's in GT core I'll use that version in RF. If it's in `test` then I'll have to have my own copy of it.

**Comment by pomadchin** [comment]
I'm good with it; think we need to merge it.
