### PR TITLE
Expose Charset in a ShapeFileReader API

### LINKED ISSUE #3445: `ShapefileReader` in geotrellis-shapefile implicitly assumes ISO-8859-1 character encoding and does not read shapefiles with UTF-8 (or other charset) contents correctly
## Describe the bug

When reading an ESRI shapefile that contains UTF-8 characters (e.g., foreign language properties), the data (properties) can look garbled. In fact, the reader is implicitly assuming the ISO-8859-1 character encoding via the geotools dependency.

## Expected behavior

When reading ESRI shapefiles with UTF-8 characters, all characters should be read properly, possibly after caller sets the correct character set.

## Environment

- Java version: 17
- Scala version: 2.13
- GeoTrellis version: 3.7.0-SNAPSHOT

## Additional context

The issue arises here: https://github.com/locationtech/geotrellis/blob/8541e5d97cdef71f6cd239cb6bb54a520e192002/shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala#L52

By default, geotools's data store expects ISO-8859-1 as a string encoding:
https://github.com/sigcorporativo-ja/panelGestion/blob/318def8a9eb1168d7bae9ee2c126fd8ff0c42129/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java#L143

geotools provides a `setCharset(charset: java.nio.charset.Charset)` method on data stores if you have properties other than ISO-8859-1. This way user can set the character set if they choose.

I propose an alternate implementation of `readSimpleFeatures` and appropriate modifications to/additions of helper functions:
```scala
  def readSimpleFeatures(
      url: URL,
      charSet: java.nio.charset.Charset
  ): Seq[SimpleFeature] = {
    // Extract the features as GeoTools 'SimpleFeatures'
    val ds = new ShapefileDataStore(url)
    ds.setCharset(charSet)
    val ftItr: SimpleFeatureIterator = ds.getFeatureSource.getFeatures.features

    try {
      val simpleFeatures = scala.collection.mutable.ListBuffer[SimpleFeature]()
      while (ftItr.hasNext) simpleFeatures += ftItr.next()
      simpleFeatures.toList
    } finally {
      ftItr.close
      ds.dispose
    }
  }
```

This works fine for me and is what I am using in my project. I regret that I cannot share a sample file, but I am not permitted to do that with the data I have. You can test it well enough by making a layer with properties that have e.g. Chinese or Korean characters.

### PR DESCRIPTION
**Pull request by vlulla**
# Overview

This PR makes charset configurable, but defaults to `ISO-8859-1` in order not to change bahavior of the old functions.

## Checklist

- [x] [./CHANGELOG.md](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary. Link to the issue if closed, otherwise the PR.
- [x] Unit tests added for bug-fix or new feature

Closes #3445

### CODE REVIEW

File: shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala [hunk 1]
```diff
@@ -47,9 +48,10 @@ object ShapeFileReader {
 
   def readSimpleFeatures(path: String): Seq[SimpleFeature] = readSimpleFeatures(new URL(s"file://${new File(path).getAbsolutePath}"))
 
-  def readSimpleFeatures(url: URL): Seq[SimpleFeature] = {
+  def readSimpleFeatures(url: URL, charSet: Charset = Charset.forName("ISO-8859-1")): Seq[SimpleFeature] = {
```
Comment (pomadchin) [inline shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala:51]: Hm, unfortunately, this breaks compatability, the signature of this function will be slighely different. 

I want to suggest to have here two functions:

```scala
def readSimpleFeatures(url: URL, charSet: Charset): Seq[SimpleFeature] = ??? // which will use the charset
// for the backwards compat
def readSimpleFeatures(url: URL): Seq[SimpleFeature] =  readSimpleFeatures(url, Charset.forName("ISO-8859-1"))
```

File: shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala [hunk 2]
```diff
@@ -31,5 +34,17 @@ class ShapeFileReaderSpec extends AnyFunSpec with Matchers {
         data.keys.toSeq should be (Seq("LowIncome", "gbcode", "ename", "WorkingAge", "TotalPop", "Employment"))
       }
     }
+
+  }
+
+  describe("Issue 3445") {
+    it("should read SimpleFeatures with different charSet") {
+      val url = new URL("https://github.com/locationtech/geotrellis/raw/master/shapefile/data/shapefiles/demographics/demographics.shp")
```
Comment (pomadchin) [inline shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala:42]: I'm wondering, could we put it into the `resources` folder? What is the size of it?

**Review by pomadchin — CHANGES_REQUESTED** [review]
Thanks for a nice PR! 

I left a couple of comments, only one of them is critical. 

Could I ask you to sign [ECA](https://github.com/locationtech/geotrellis/blob/master/docs/CONTRIBUTING.rst#eclipse-contributor-agreement-eca) please to make Eclipse license checker happy?

(Eclipse grabs your name and email from the commit, so doublecheck that you commited under the correct email (that was used to sign ECA), right now the ECA is required for (v*l*la@****.com) email).

File: shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala (hunk 2 above)
Comment (vlulla) [reply shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala:42]: Since the other test was already using the shapefile from the `shapefile/data` folder I didn't bother to mess around with it. I'm just using the URL path here because that's what the signature for `readSimpleFeatures` requires.

File: shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala (hunk 1 above)
Comment (vlulla) [reply shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala:51]: I have made the change but want to wait before I sort out the ECA issues. I have signed the general ECA but not project specific agreement. Apparently, I cannot see the "Committer Tools" link on the right hand side that is described in the contributing documentation.

File: shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala [hunk 3]
```diff
@@ -31,5 +34,17 @@ class ShapeFileReaderSpec extends AnyFunSpec with Matchers {
...
+      val features = ShapefileReader.readSimpleFeatures(url)
```
Comment (pomadchin) [inline shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala:43]: There is a typo! `ShapefileReader => ShapeFileReader`

**Comment by pomadchin** [comment]
Let's do the following:

1. We need a test that reproduces the error
2. We need a test that makes sure that the reproduced error is fixed
3. It looks like the change is slighly larger than two methods addition:

```scala
def readSimpleFeatures(path: String): Seq[SimpleFeature] = readSimpleFeatures(new URL(s"file://${new File(path).getAbsolutePath}"), DEFAULT_CHARSET)
def readSimpleFeatures(path: String, charSet: Charset): Seq[SimpleFeature] = readSimpleFeatures(new URL(s"file://${new File(path).getAbsolutePath}"), charSet)

def readSimpleFeatures(url: URL): Seq[SimpleFeature] = readSimpleFeatures(url, DEFAULT_CHARSET)
def readSimpleFeatures(url: URL, charSet: Charset): Seq[SimpleFeature] = ???

// but also all user API methods should have overloads

// ... (just an example below, all polygon methods should have the charset support) 
def readMultiPolygonFeatures(path: String): Seq[MultiPolygonFeature[Map[String,Object]]] =
  readMultiPolygonFeatures(path, DEFAULT_CHARSET)
def readMultiPolygonFeatures(path: String, charSet: Charset): Seq[MultiPolygonFeature[Map[String,Object]]] =
  readSimpleFeatures(path, charSet)
    .flatMap { ft => ft.geom[MultiPolygon].map(MultiPolygonFeature(_, ft.attributeMap)) }
// ...
  ```
  
The test may look this way:

```scala
class ShapeFileReaderSpec extends AnyFunSpec with Matchers {
  describe("ShapeFileReader") {
    it("should read MultiPolygons feature attributes") {
      val path = "shapefile/data/shapefiles/demographics/demographics.shp"
      val features = ShapeFileReader.readMultiPolygonFeatures(path)
      features.size should be (160)
      for(MultiPolygonFeature(_: MultiPolygon, data: Map[String, Object]) <- features) {
        data.keys.toSeq should be (Seq("LowIncome", "gbcode", "ename", "WorkingAge", "TotalPop", "Employment"))
      }
    }

    // https://github.com/locationtech/geotrellis/issues/3445
    it("should read UTF-8 MultiPolygons feature attributes") {
      val path = "shapefile/data/shapefiles/demographics-utf8/demographics.shp"
      val features = ShapeFileReader.readMultiPolygonFeatures(path, Charset.forName("UTF-8"))
      features.size should be (160)

      features.take(4).map(_.data("ename").asInstanceOf[String]) shouldBe Seq("南关街道", "七里烟香", "谢庄镇", "Cheng Guan Zhen")
    }
  }
}
```

Note: I pushed a test file that should work with the test above.

File: shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala [hunk 4]
```diff
@@ -31,5 +34,19 @@ class ShapeFileReaderSpec extends AnyFunSpec with Matchers {
...
+    it("should read UTF-8 MultiPolygons feature attributes") {
+      val path = "shapefile/data/shapefiles/demographics-utf8/demographics.shp"
+      val features = ShapeFileReader.readMultiPolygonFeatures(path, Charset.forName("UTF-8"))
+      features.size should be (160)
+
+      features.take(4).map(_.data("ename").asInstanceOf[String]) shouldBe Seq("南关街道", "七里烟香", "谢庄镇", "Cheng Guan Zhen")
+
+      val featuresInvalid = ShapeFileReader.readMultiPolygonFeatures(path)
+      val enames = featuresInvalid.take(4).map(_.data("ename").asInstanceOf[String])
+      // println(s""" ${enames.map(x => s"«${x}»").mkString(" <=> ")} """)
```
Comment (pomadchin) [inline shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala:48]: oh, is it a test code and should be removed?

Comment (vlulla) [reply shapefile/src/test/scala/geotrellis/shapefile/ShapeFileReaderSpec.scala:48]: You mean line 48, right? Nathan also brought it up. I forgot to remove it...sorry.

**Comment by vlulla** [comment]
Thank you for the patient guidance! It has been very educational.

**Comment by axb21** [comment]
Ah great! I said in the other issue that I'd make a pull request for this but then got distracted by life. Sorry about that, but I'm glad to see @vlulla jumped in and did it!
