### PR TITLE
Haversine formula fix

### LINKED ISSUE #2383: Haversine formula has bugs
The Haversine formula in ZoomedLayoutScheme seems to have a bug in it; I was using that logic to compute road distance metrics on OSM ways and found odd results. When I changed the implementation to something that [matched this](https://github.com/njj/haversine/blob/master/haversine.js), I started getting sensible results. 

We should move to something like:

```scala
    val R = EARTH_RADIUS
    val (start, end) = (ll1, ll2)
    val dLat = math.toRadians(end.y - start.y)
    val dLon = math.toRadians(end.x - start.x)
    val lat1 = math.toRadians(start.y)
    val lat2 = math.toRadians(end.y)

    val a = math.sin(dLat/2) * math.sin(dLat/2) +
            math.sin(dLon/2) * math.sin(dLon/2) * math.cos(lat1) * math.cos(lat2)
    val c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))

    R * c
```

This only would effect area measurements for points that do not have valid UTM zones, so probably doesn't have a huge effect.

We should put the distance formula in geotrellis.utils or geotrellis.vector, so that it can be used outside of the ZoomedLayoutScheme logic.

### PR DESCRIPTION
**Pull request by pomadchin**
Fixes #2383

### CODE REVIEW

File: util/src/main/scala/geotrellis/util/Haversine.scala [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package geotrellis.util
+
+object Haversine {
+  val EARTH_RADIUS = 6378137d // Use what gdal2tiles uses.
```
Comment (metasim) [inline util/src/main/scala/geotrellis/util/Haversine.scala]: I'd suggest adding a doc comment declaring the units used.

File: util/src/main/scala/geotrellis/util/Haversine.scala [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+  // (x: Double, y: Double) points
+  def apply(start: (Double, Double), end: (Double, Double), R: Double = EARTH_RADIUS): Double = {
```
Comment (metasim) [inline util/src/main/scala/geotrellis/util/Haversine.scala]: For future GeoTrellisites, I'd suggest a doc comment indicating what the components of `start` and `end` are. e.g. (Latitude, Longitude), or (Longitude, Latitude) or (radius, angle), etc.

File: vector/src/main/scala/geotrellis/vector/Point.scala [hunk 3]
```diff
@@ -31,6 +31,9 @@ object Point {
 
   implicit def jtsCoord2Point(coord: jts.Coordinate): Point =
     Point(factory.createPoint(coord))
+
+  implicit def pointToTuple2(point: Point): (Double, Double) =
```
Comment (metasim) [inline vector/src/main/scala/geotrellis/vector/Point.scala]: While this is a nice convenience for people familiar with the particular code that translates between `Point` and `Tuple2`, I've been burned enough by unexpected or unintended conversions in the past to avoid this sort of thing personally, especially when the conversion is to a more general type. If you were converting between `Point` and something like `Position(lat, lng)` I'd be a bit less concerned because the translation semantics of `x` -> `lat` and `y` -> `lng` are clear, but `_1` and `_2` have no inherent semantics and therefore information is lost in the implicit conversion.

Comment (pomadchin) [reply vector/src/main/scala/geotrellis/vector/Point.scala]: Yes, i decided to remove this implicit at all as it is indeed ambiguous.

**Comment by pomadchin** [comment]
@metasim do you have some additional comments?
