### PR TITLE
Fix CRS parser and proj4 cea projection support

### LINKED ISSUE #1415: Not possible ingest tiles in some source projections.
Ingest issue can be repeated by using this projection:

``` bash
+proj=cea +lon_0=-117.333333333333 +lat_ts=33.75 +x_0=0 +y_0=0 +datum=NAD27 +units=m +no_defs
```

Or even projection with EPSG code (we have it in our proj4 tests):

``` bash
# NSIDC EASE-Grid Global
<3410> +proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +a=6371228 +b=6371228 +units=m +no_defs  <>
```

Probably there are more projections, we have to check out possible bugs more accurate.

### PR DESCRIPTION
**Pull request by pomadchin**
Fixes #1415

### CODE REVIEW

File: raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala [hunk 1]
```diff
@@ -283,5 +283,13 @@ class ReprojectSpec extends FunSpec
 
       windowedReproject.rasterExtent should be (regularReproject.rasterExtent)
     }
+
+    it ("should reproject cea projection into WebMercator correctly") {
+      val geoTiff = SinglebandGeoTiff(geoTiffPath("reproject/cea.tif"))
+      val raster = geoTiff.raster.reproject(geoTiff.crs, WebMercator)
+
+      geoTiff.crs.toProj4String should be ("+proj=cea +lat_ts=33.75 +lon_0=-117.333333333333 +x_0=0.0 +y_0=0.0 +datum=NAD27 +units=m ")
+      raster.extent should be (geoTiff.extent.reproject(geoTiff.crs, WebMercator))
```
Comment (pomadchin) [inline raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala]: This test would fail, is it expected? @echeipesh @lossyrob 

```
- should reproject cea projection into WebMercator correctly *** FAILED ***
[info]   Extent(-1.308996986113024E7, 5120515.980949544, -1.3059127661588239E7, 5176329.847734357) was not equal to Extent(-1.3089964868731003E7, 5120540.114447579, -1.3059110371614724E7, 5176329.847734357) (ReprojectSpec.scala:294)
```

**Comment by pomadchin** [comment]
This PR fixes https://github.com/biggis-project/biggis-landuse/issues/2 and cea projection support (before it produced black tile or even could not reproject anything). But this PR introduces a new question.

The rasters below:

(original in cea projection)
image

(reprojected into WebMercator via gdal)
image

(reprojected into WebMercator via GeoTrellis)
image

The question is where is the mistake? In proj4j library (though i tried to check various of `CylindricalEqualAreaProjection` implementations in proj4, proj4js and jmaprojlib) or in GDAL (i don't think its a gdal issue though)?

For sure this bug (if it's a bug) can be addressed in a separate PR.

**Comment by jbouffard** [comment]
The mistake appears to be with GeoTrellis. Using pyproj, this is the results that I get

``` 
In [21]: cea_box = box(-28493.167, 4255884.544, 2358.212, 4224973.143)

In [22]: project = partial(
    ...:     pyproj.transform,
    ...:     pyproj.Proj('+proj=cea +lat_ts=33.75 +lon_0=-117.333333333333 +x_0=0.0 +y_0=0.0 +datum=NAD27 +units=m '),
    ...:     pyproj.Proj('+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=
    ...: @null +wktext +no_defs'))

In [23]: transform(project, cea_box).bounds
Out[23]: 
(-13095817.8097412,
 3983903.7592389523,
 -13058750.785876077,
 4021262.7490324154)
```

This matches what GDAL returns, but differs in what GeoTrellis calculates.

**Comment by pomadchin** [comment]
I'll dig into it a bit more tomorrow

**Comment by pomadchin** [comment]
(reprojected into WebMercator via GeoTrellis)
image

**Comment by pomadchin** [comment]
Fixed proj4j tests in `proj4-epsg.csv` (tests set to *passing*):

* EPSG:4326→EPSG:3410 
* EPSG:4326→EPSG:3975
* EPSG:4326→EPSG:6933
